apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: quarkus-department
  name: quarkus-department
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quarkus-department
  template:
    metadata:
      labels:
        app: quarkus-department
    spec:
      initContainers:
        - name: init-migration
          image: gradle:jdk11-alpine
          command: ['gradle', '-version']
      containers:
        - name: quarkus-department
          image: quarkus/quarkus-kotlin-jvm
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
              protocol: TCP

